#!/bin/bash

set -e
set -x

deactivate || true
rm -rf env/
python3 -m venv env
source env/bin/activate
pip install -r requirements.txt
pip freeze | sort > requirements.txt
pip install -r requirements-dev.txt
pip freeze | sort > /tmp/requirements-all.txt
comm -13 requirements.txt /tmp/requirements-all.txt | sort > requirements-dev.txt
